import { createSlice } from "@reduxjs/toolkit";

const slice = createSlice({
  name: "electronicShop",
  initialState: [
    {
      id: 1,
      productImage: "1.jpg",
      productName: "YOUNG SHOP",
      productInfor: "LG White Front Load Steam Washer",
      productPrices: "$1,422.7",
      saleOff: "-39%",
      discount: "$1,025.5",
      starColorOn: "#fbb901",
      starColorOff: "lightgrey",
      percentage: 80,
      productSold: 10,
    },
    {
      id: 2,
      productImage: "2.jpg",
      productName: "YOUNG SHOP",
      productInfor: "Edifier Powered Bookshelf Speakers",
      productPrices: "$96",
      saleOff: "-13%",
      discount: "$85",
      starColorOn: "#fbb901",
      starColorOff: "lightgrey",
      percentage: 70,
      productSold: 15,
    },
    {
      id: 3,
      productImage: "3.jpg",
      productName: "YOUNG SHOP",
      productInfor: "Amcrest Security Camera in White Color",
      productPrices: "$62.99",
      saleOff: "-37%",
      discount: "$45.9",
      starColorOn: "#fbb901",
      starColorOff: "lightgrey",
      percentage: 70,
      productSold: 20,
    },
    {
      id: 4,
      productImage: "4.jpg",
      productName: "YOUNG SHOP",
      productInfor: "Grand Slam Indoor Of Show Jumping Novel",
      productPrices: "$41.99",
      saleOff: "-27%",
      discount: "$32.99",
      starColorOn: "#fbb901",
      starColorOff: "lightgrey",
      percentage: 70,
      productSold: 22,
    },
    {
      id: 5,
      productImage: "5.jpg",
      productName: "YOUNG SHOP",
      productInfor: "Sound Intone I65 Earphone White Version",
      productPrices: "$106.96",
      saleOff: "-6%",
      discount: "$100.99",
      starColorOn: "#fbb901",
      starColorOff: "lightgrey",
      percentage: 90,
      productSold: 10,
    },
    {
      id: 6,
      productImage: "6.jpg",
      productName: "YOUNG SHOP",
      productInfor: "Korea Long Sofa Fabric In Blue Navy Color",
      productPrices: "$670.2",
      saleOff: "-18%",
      discount: "$567.8",
      starColorOn: "#fbb901",
      starColorOff: "lightgrey",
      percentage: 100,
      productSold: 79,
    },
  ],
  reducers: {},
});
export default slice;
